name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."212.64.215.155:30835"]
              http = true
              insecure = true              

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: api
          push: true
          tags: 212.64.215.155:30835/authservice:latest
          cache-from: type=registry,ref=212.64.215.155:30835/authservice:latest
          cache-to: type=inline

